task:
  matrix:
    - macos_instance:
        image: ghcr.io/cirruslabs/macos-sonoma-base:latest
    - container:
        image: gcc:latest
  make_script: make
  test_script: make test
  install_script: make install

