task:
  matrix:
    - macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
    - container:
        image: gcc:latest
  make_script: make
  test_script: make test
  install_script: which sudo && sudo make install || make install

